/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MapService_constants.h"

namespace around7 { namespace mapservice {

const MapServiceConstants g_MapService_constants;

MapServiceConstants::MapServiceConstants() {
}

}} // namespace

