/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MapService_CONSTANTS_H
#define MapService_CONSTANTS_H

#include "MapService_types.h"

namespace around7 { namespace mapservice {

class MapServiceConstants {
 public:
  MapServiceConstants();

};

extern const MapServiceConstants g_MapService_constants;

}} // namespace

#endif
